### ISSUE TITLE
Feature: Update `// @deno-types="..."`

### ISSUE THREAD

**Issue by Milly** [hasundue/molt#184]
Feature request.
When using `npm:` packages, we may need to get types from `@types/...`. It would be nice to be able to update the package version in special comments like following:

```ts
// @deno-types="npm:@types/foo@1.2.3"
import { foo } from "npm:foo@1.3.9";
```

If this special comment is present, deno will write the package information into the *deno.lock* file just as if it were a package specified in a normal import statement.

**Comment by hasundue** [comment]
I've been overlooked that. Thanks for pointing it out.
