### ISSUE TITLE
Plain text changelog

### ISSUE THREAD

**Issue by dkolba** [hasundue/molt#189]
I use molt in a custom GitHub Action Workflow and generate changelog output in CI for automatic PRs, which look like this:

```

📦 [1m@std/http[22m [33m0.224.0[39m => [33m0.224.4[39m
  [90mdeno.json[39m
📦 [1m@std/log[22m [33m0.224.0[39m => [33m0.224.2[39m
  [90mdeno.json[39m
📦 [1mesm.sh/*@preact/signals[22m [33m1.2.2[39m => [33m1.2.3[39m
  [90mdeno.json[39m
📦 [1mlightningcss[22m [33m[39m => [33m1.25.1[39m
  [90msparkle.ts[39m
```

Is it possible to display the changelog in plain text (without ANSI formatting)?

**Comment by hasundue** [comment]
Well, I believe `NO_COLOR=1 deno run ...` just works, so we shouldn't need to introduce extra complexity for that.

**Comment by dkolba** [comment]
@hasundue yes, this was what I was looking for, thanks! 👍
