### ISSUE TITLE
Can't update a lock file in some cases

### ISSUE THREAD

**Issue by 5ouma** [hasundue/molt#191]
I tried to update the `deno.json` and `deno.lock` by `molt deno.json -w --unstable-lock` and molt-action. It says this and outputs an error.
```
Can't update a lockfile for an import map including any URL that can'be imported as is.
```

These might be the factors that reproduce this.
- `deno.json` includes:
  - non-official URL import like `https://esm.sh/@octokit/rest@20.1.1`
  - or a special version specified import like `jsr:@std/http@~0.223/user-agent`
- `deno.lock` exists (if not, it runs correctly even if `deno.json` has the above imports.)

<br />

ref:
- success: https://github.com/5ouma/opml-generator/actions/runs/9557327375/job/26344469161
- failed: https://github.com/5ouma/reproxy/actions/runs/9557174831/job/26343806710

**Comment by 5ouma** [comment]
The code that outputs this message is here.
https://github.com/hasundue/molt/blob/dfe31680d2ef102bab2d4867d2631e7178598623/core/update.ts#L421-L436

**Comment by hasundue** [comment]
I'm aware of the issue, and was just working on it today, but your additional information helps a lot! Thanks for reporting.
