### ISSUE TITLE
Support for bumping version ranges

### ISSUE THREAD

**Issue by brc-dd** [hasundue/molt#194]
It's currently stated in the readme that

> Molt does NOT bump version ranges like `1`, `1.x`, `~1.2.3` and `^1.2.3` in
> `npm:` and `jsr:` specifiers, but only updates a lockfile.

I would like to understand the reasoning behind that. For versions like `^1.0.0` with latest version `1.2.3` it might make sense, but in cases where the version range doesn't satisfy the latest available version molt won't bump it, for example most of the deno_std packages - when they release a minor, some range like `^0.200.0` won't satisfy it and lock file won't be updated either.

**Comment by hasundue** [comment]
Thanks! I totally agree with you and this will be supported in the next release (0.19.0).
The implementation is already done [here](
https://github.com/hasundue/molt/tree/fix-lock-write) but needs finalization to be published.

**Comment by brc-dd** [comment]
Ah sorry, I should have looked more 😅 Thanks for your work!
