### ISSUE TITLE
Support for pre-release versions

### ISSUE THREAD

**Issue by brc-dd** [hasundue/molt#195]
Molt currently doesn't update dependencies like `jsr:@cliffy/command@1.0.0-rc.4` to `jsr:@cliffy/command@1.0.0-rc.5`.

If there is a stable version available, it even downgrades them:

```sh
~/foo
❯ cat deno.json
{
  "imports": {
    "@std/http": "jsr:@std/http@1.0.0-rc.4"
  }
}

~/foo
❯ deno run -A jsr:@molt/cli deno.json
📦 @std/http 1.0.0-rc.4 => 0.224.5
```

**Comment by hasundue** [comment]
As #194, this will also be supported in the next minor release :+1:

**Comment by hasundue** [comment]
As a workaround right now, you may `--ignore` such dependencies. Sorry for inconvenience though
